use crate::cli::executor::{docker_host, CliExecutor};
use std::path::PathBuf;

const DOCKER: &str = "/opt/homebrew/bin/docker";
const GATEWAY_CONTAINER: &str = "colima-gateway";
const GATEWAY_NETWORK: &str = "colima-gateway-net";
const TRAEFIK_IMAGE: &str = "traefik:v3.4";

/// Directory inside the Traefik container where file-provider configs are read.
const TRAEFIK_DYNAMIC_DIR: &str = "/etc/traefik/dynamic";

/// Return the host-side directory used to store Traefik dynamic config files.
pub fn dynamic_config_dir() -> Result<PathBuf, String> {
    let config_dir = dirs::config_dir().ok_or("Cannot find config directory")?;
    let dir = config_dir.join("colima-desktop").join("gateway");
    std::fs::create_dir_all(&dir)
        .map_err(|e| format!("Failed to create gateway config dir: {}", e))?;
    Ok(dir)
}

/// Ensure the shared Docker network exists.
async fn ensure_network() -> Result<(), String> {
    let docker_host_val = docker_host();
    // Check if network exists
    let result = CliExecutor::run(
        DOCKER,
        &["network", "inspect", GATEWAY_NETWORK],
    )
    .await;

    if result.is_err() {
        // Create it
        tokio::process::Command::new(DOCKER)
            .args(["network", "create", GATEWAY_NETWORK])
            .env("DOCKER_HOST", &docker_host_val)
            .output()
            .await
            .map_err(|e| format!("Failed to create gateway network: {}", e))?;
    }

    Ok(())
}

/// Start the Traefik gateway container.
pub async fn start_gateway() -> Result<(), String> {
    let docker_host_val = docker_host();

    // If already running, skip
    if is_gateway_running().await {
        return Ok(());
    }

    ensure_network().await?;

    let config_dir = dynamic_config_dir()?;
    let config_mount = format!("{}:{}", config_dir.display(), TRAEFIK_DYNAMIC_DIR);

    // Write static Traefik config
    let static_config = format!(
        r#"# Auto-generated by Colima Desktop
entryPoints:
  web:
    address: ":80"

providers:
  file:
    directory: "{}"
    watch: true

log:
  level: "WARN"

api:
  insecure: false
"#,
        TRAEFIK_DYNAMIC_DIR
    );

    let static_config_path = config_dir.join("..").join("traefik.yml");
    let static_config_path = static_config_path
        .canonicalize()
        .unwrap_or_else(|_| config_dir.parent().unwrap().join("traefik.yml"));

    // Ensure parent exists
    if let Some(parent) = static_config_path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("Failed to create traefik config dir: {}", e))?;
    }

    std::fs::write(&static_config_path, &static_config)
        .map_err(|e| format!("Failed to write traefik.yml: {}", e))?;

    let static_mount = format!(
        "{}:/etc/traefik/traefik.yml:ro",
        static_config_path.display()
    );

    // Remove stale container if exists
    let _ = CliExecutor::run(DOCKER, &["rm", "-f", GATEWAY_CONTAINER]).await;

    // Start Traefik
    let output = tokio::process::Command::new(DOCKER)
        .args([
            "run",
            "-d",
            "--name",
            GATEWAY_CONTAINER,
            "--network",
            GATEWAY_NETWORK,
            "-p",
            "80:80",
            "-v",
            &config_mount,
            "-v",
            &static_mount,
            "--restart",
            "unless-stopped",
            TRAEFIK_IMAGE,
        ])
        .env("DOCKER_HOST", &docker_host_val)
        .output()
        .await
        .map_err(|e| format!("Failed to start gateway: {}", e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("Failed to start gateway: {}", stderr));
    }

    Ok(())
}

/// Stop and remove the gateway container.
pub async fn stop_gateway() -> Result<(), String> {
    let _ = CliExecutor::run(DOCKER, &["rm", "-f", GATEWAY_CONTAINER]).await;
    Ok(())
}

/// Check if the gateway container is running.
pub async fn is_gateway_running() -> bool {
    CliExecutor::run(
        DOCKER,
        &[
            "ps",
            "-q",
            "--filter",
            &format!("name={}", GATEWAY_CONTAINER),
            "--filter",
            "status=running",
        ],
    )
    .await
    .map(|out| !out.trim().is_empty())
    .unwrap_or(false)
}

/// Connect an existing container to the gateway network so Traefik can reach it.
pub async fn connect_container(container_name: &str) -> Result<(), String> {
    let docker_host_val = docker_host();
    let output = tokio::process::Command::new(DOCKER)
        .args([
            "network",
            "connect",
            GATEWAY_NETWORK,
            container_name,
        ])
        .env("DOCKER_HOST", &docker_host_val)
        .output()
        .await
        .map_err(|e| format!("Failed to connect container: {}", e))?;

    // Ignore "already connected" error
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        if !stderr.contains("already exists") {
            return Err(format!("Failed to connect {}: {}", container_name, stderr));
        }
    }

    Ok(())
}

/// Get a container's IP address on the gateway network.
pub async fn get_container_ip(container_name: &str) -> Result<String, String> {
    // Use `index` for network names with hyphens (Go template syntax)
    let format = format!(
        "{{{{(index .NetworkSettings.Networks \"{}\").IPAddress}}}}",
        GATEWAY_NETWORK
    );
    let ip = CliExecutor::run(
        DOCKER,
        &["inspect", "--format", &format, container_name],
    )
    .await
    .map_err(|e| format!("Failed to inspect {}: {}", container_name, e))?;

    let ip = ip.trim().to_string();
    if ip.is_empty() {
        return Err(format!(
            "Container {} has no IP on network {}",
            container_name, GATEWAY_NETWORK
        ));
    }

    Ok(ip)
}

/// Write a Traefik dynamic config file for a specific route.
pub fn write_route_config(
    hostname: &str,
    domain: &str,
    container_ip: &str,
    port: u16,
) -> Result<(), String> {
    let config_dir = dynamic_config_dir()?;
    let safe_name = hostname.replace('.', "-");

    let yaml = format!(
        r#"# Auto-generated by Colima Desktop for {domain}
http:
  routers:
    {name}:
      rule: "Host(`{domain}`)"
      entryPoints:
        - web
      service: {name}
  services:
    {name}:
      loadBalancer:
        servers:
          - url: "http://{ip}:{port}"
"#,
        domain = domain,
        name = safe_name,
        ip = container_ip,
        port = port,
    );

    let path = config_dir.join(format!("{}.yml", safe_name));
    std::fs::write(&path, yaml)
        .map_err(|e| format!("Failed to write route config: {}", e))?;

    Ok(())
}

/// Remove a route config file.
pub fn remove_route_config(hostname: &str) -> Result<(), String> {
    let config_dir = dynamic_config_dir()?;
    let safe_name = hostname.replace('.', "-");
    let path = config_dir.join(format!("{}.yml", safe_name));
    if path.exists() {
        std::fs::remove_file(&path)
            .map_err(|e| format!("Failed to remove route config: {}", e))?;
    }
    Ok(())
}

/// Clear all route config files.
pub fn clear_route_configs() -> Result<(), String> {
    let config_dir = dynamic_config_dir()?;
    if let Ok(entries) = std::fs::read_dir(&config_dir) {
        for entry in entries.flatten() {
            if entry.path().extension().map(|e| e == "yml").unwrap_or(false) {
                let _ = std::fs::remove_file(entry.path());
            }
        }
    }
    Ok(())
}
